name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
    branches: [master]

jobs:
  bof-build:
    name: Build and publish tagged release
    if: startsWith( github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    container:
      image: freefirex2/ts_bof_builder@sha256:e203ba628c97abb51ef65914b216fa1e088401710107027c353d15f09e0cfb62
    timeout-minutes: 10
    steps:
      - name: OS Packages
        run: dnf install -y jq

      - name: Minisign
        run: |
          MINISIGN_TMP=`mktemp -d`
          cd $MINISIGN_TMP
          curl -sL -o minisign-linux-amd64.tar.gz https://github.com/aead/minisign/releases/download/v0.2.0/minisign-linux-amd64.tar.gz
          tar xvf minisign-linux-amd64.tar.gz
          mv ./minisign ~/minisign
          touch ~/minisign.key && chmod 600 ~/minisign.key
          echo -e "${{ secrets.MINISIGN_PRIVATE_KEY }}" > ~/minisign.key

      - name: Check out code
        uses: actions/checkout@v2

      - name: Git Fetch Tags
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --prune --unshallow --tags -f

      - name: Packages Setup
        run: |
          mkdir packages

      - name: ProcessDestroy
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh ProcessDestroy Remote

      - name: ProcessListHandles
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh ProcessListHandles Remote
          
      - name: adcs_request
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh adcs_request Remote

      - name: adduser
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh adduser Remote

      - name: addusertogroup
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh addusertogroup Remote

      - name: chromeKey
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh chromeKey Remote

      - name: enableuser
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh enableuser Remote

      - name: office_tokens
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh office_tokens Remote

      - name: procdump
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh procdump Remote

      - name: reg_delete
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh reg_delete Remote

      - name: reg_save
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh reg_save Remote

      - name: reg_set
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh reg_set Remote

      - name: sc_config
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh sc_config Remote

      - name: sc_create
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh sc_create Remote

      - name: sc_delete
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh sc_delete Remote

      - name: sc_description
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh sc_description Remote

      - name: sc_start
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh sc_start Remote

      - name: sc_stop
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh sc_stop Remote

      - name: schtaskscreate
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh schtaskscreate Remote

      - name: schtasksdelete
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh schtasksdelete Remote

      - name: schtasksrun
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh schtasksrun Remote

      - name: schtasksstop
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh schtasksstop Remote

      - name: setuserpass
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh setuserpass Remote

      - name: shspawnas
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh shspawnas Remote

      - name: suspendresume
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh suspendresume Remote

      - name: unexpireuser
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh unexpireuser Remote

      - name: get_priv
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh get_priv Remote

      - name: sc_failure
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh sc_failure Remote

      - name: slack_cookie
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh slack_cookie Remote

      - name: adcs_request_on_behalf
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh adcs_request_on_behalf Remote

      - name: global_unprotect
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh global_unprotect Remote

      - name: make_token_cert
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh make_token_cert Remote

      - name: slackKey
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh slackKey Remote

      - name: ask_mfa
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh ask_mfa Remote

      - name: disableuser
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh disableuser Remote

      - name: get_azure_token
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh get_azure_token Remote

      - name: shutdown
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh shutdown Remote

      - name: clipboard
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh clipboard Injection

      - name: conhost
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh conhost Injection

      - name: createremotethread
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh createremotethread Injection

      - name: ctray
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh ctray Injection

      - name: dde
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh dde Injection

      - name: kernelcallbacktable
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh kernelcallbacktable Injection

      - name: ntcreatethread
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh ntcreatethread Injection

      - name: ntqueueapcthread
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh ntqueueapcthread Injection

      - name: setthreadcontext
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh setthreadcontext Injection

      - name: svcctrl
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh svcctrl Injection

      - name: tooltip
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh tooltip Injection

      - name: uxsubclassinfo
        run: |
          chmod +x ./make_bof.sh
          ./make_bof.sh uxsubclassinfo Injection

      - name: "Publish Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./packages/*.tar.gz
            ./packages/*.minisig